# Generated by Django 4.0.4 on 2022-05-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_videoallproxy_options_and_more'),
        ('playlists', '0003_playlist_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='video',
        ),
        migrations.AddField(
            model_name='playlist',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='playlist_featured', to='videos.video'),
        ),
    ]
