# Generated by Django 4.0.4 on 2022-05-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_videoallproxy_options_and_more'),
        ('playlists', '0004_remove_playlist_videos_remove_playlist_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='playlist_item', to='videos.video'),
        ),
    ]
