# Generated by Django 4.0.4 on 2022-05-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0006_playlist_videos_remove_playlist_video_playlist_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
    ]
