# Generated by Django 4.0.4 on 2022-05-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0012_movieproxy_alter_playlist_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieproxy',
            options={'verbose_name': 'Movie ', 'verbose_name_plural': 'Movies'},
        ),
    ]
