# Generated by Django 4.0.5 on 2022-06-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0017_alter_playlist_related_alter_playlistrelated_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistrelated',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
